version: '2.5'

services:
  php-onemart:
    container_name: php-onemart
    restart: always
    build: .
    volumes:
      - ./:/home
    ports:
      - 8000:8000
  mysql-onemart:
    container_name: mysql-onemart
    image: mysql
    volumes:
      - ~/mysql/onemart:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ma_bd
      MYSQL_USER: mon_user
      MYSQL_PASSWORD: mon_user
    ports:
      - 3300:3306
