version: '2.5'

services:
  php-apache:
    container_name: php-8-container
    build: .
    volumes:
      - ./:/home
    ports:
      - 8000:80 
  mysql_service:
    container_name: mysql_container
    image: mysql
    volumes:
      - /home/tuoadama/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3300:3306